{% set name = "neuroglancer" %}
{% set version = "2.41.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neuroglancer-{{ version }}.tar.gz
  sha256: 2c519da54169d141053e14940115f4b4cbdf88d24a9114cd3ae236ea62f16216

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation --no-index -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp           # [osx]
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python
    - numpy
    - llvm-openmp           # [osx]
    - nodejs
    - atomicwrites >=1.4.1
    - google-apitools >=0.5.32
    - google-auth >=2.38.0
    - pillow >=3.2.0
    - requests >=2.32.3
    - tornado >=6.4.2

test:
  imports:
    - neuroglancer
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/google/neuroglancer
  summary: 'Python integration for neuroglancer, a WebGL-based viewer for volumetric data'
  description: |
    Neuroglancer is a WebGL-based viewer for volumetric data.
    It is capable of displaying arbitrary (non axis-aligned) cross-sectional views of
    volumetric data, as well as 3-D meshes and line-segment based models (skeletons).
    Refer to the documentation website at https://neuroglancer-docs.web.app for more details.
    This is not an official Google product.

  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - python/ext/third_party/openmesh/OpenMesh/LICENSE

  doc_url: https://neuroglancer-docs.web.app
  dev_url: https://github.com/google/neuroglancer

extra:
  recipe-maintainers:
    - stuarteberg
