{% set name = "neuroglancer" %}
{% set version = "2.41.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/google/neuroglancer/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7fc3c19dc516cce1418fedffdc909efb76630a7aaa2f53f7dc0a50239a7c8545
  patches:
    - patches/osx-arm64/copy_openmesh_deps.py.patch  # [osx and build_platform != target_platform]

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation --no-index -vv
  number: 3

  # This package should support Windows, but the feedstock fails to build right now.
  # error: [WinError 2] The system cannot find the file specified
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - nodejs >=22,<24                        # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp           # [osx]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm >=8.1.0
    - numpy
    - nodejs-wheel >=22,<24              # [build_platform == target_platform]
  run:
    - python
    - numpy
    - llvm-openmp           # [osx]
    - nodejs
    - atomicwrites >=1.4.1
    - google-apitools >=0.5.32
    - google-auth >=2.38.0
    - pillow >=3.2.0
    - requests >=2.32.3
    - tornado >=6.4.2

test:
  imports:
    - neuroglancer
  requires:
    - pip
    - pytest
  source_files:
    - python/tests
    - testdata
  commands:
    - pip check
   # We just run tests that don't require a browser.
    - cd python/tests && pytest
      equivalence_map_test.py json_wrappers_test.py local_volume_test.py managed_layer_test.py merge_tool_test.py
      on_demand_mesh_generator_test.py url_state_test.py viewer_state_test.py write_annotations_test.py

about:
  home: https://github.com/google/neuroglancer
  summary: 'Python integration for neuroglancer, a WebGL-based viewer for volumetric data'
  description: |
    Neuroglancer is a WebGL-based viewer for volumetric data.
    It is capable of displaying arbitrary (non axis-aligned) cross-sectional views of
    volumetric data, as well as 3-D meshes and line-segment based models (skeletons).
    Refer to the documentation website at https://neuroglancer-docs.web.app for more details.
    This is not an official Google product.

  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - python/ext/third_party/openmesh/OpenMesh/LICENSE

  doc_url: https://neuroglancer-docs.web.app
  dev_url: https://github.com/google/neuroglancer

extra:
  recipe-maintainers:
    - stuarteberg
